# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u3wsETYbb-2knmrIEMQxngpViYgwiNfx
"""

import streamlit as st
import pandas as pd

# Mock data for activity summary
data = {
    "Party Name": ["Sunday Football", "Board Game Night"],
    "Activity Type": ["Football", "Board Games"],
    "Date": ["02/03/2025", "05/03/2025"],
    "Start Time": ["18:00", "19:30"],
    "Location": ["City Stadium", "Gamesmith Cafe"],
    "Participants": ["7/8", "3/4"]
}
df = pd.DataFrame(data)

st.title("Joinzy! - Activity Matching Platform")

# Activity Type Selection
st.sidebar.header("Find or Create an Activity")
activity_type = st.sidebar.selectbox("Select Activity Type", ["Football", "Board Games", "Badminton", "Basketball", "Other"])

# Buttons to Create/Search Party
col1, col2 = st.sidebar.columns(2)
with col1:
    st.button("Create Party")
with col2:
    st.button("Search Party")

st.subheader("Activity Summary")
st.dataframe(df)

# User Registration Section
st.subheader("User Registration")
with st.form("registration_form"):
    name = st.text_input("Name")
    age = st.number_input("Age", min_value=12, max_value=99)
    phone = st.text_input("Phone Number")
    gender = st.radio("Gender", ["Male", "Female", "Other"])
    selected_activity = st.multiselect("Interested Activities", ["Football", "Board Games", "Badminton", "Basketball", "Other"])
    participation_time = st.time_input("Preferred Time")
    location = st.text_input("Preferred Location")
    submit_button = st.form_submit_button("Register")

    if submit_button:
        st.success(f"Registered successfully, {name}!")

# Login Section
st.subheader("Login")
username = st.text_input("Username")
password = st.text_input("Password", type="password")
st.button("Login")

# My Bookings Section
st.subheader("My Bookings")
st.write("Your upcoming activities will be displayed here.")

# Summary Dashboard
st.subheader("Summary Dashboard")
st.write("Overview of activities, participant statistics, and discounts.")

# Activity Costs & Discounts
st.subheader("Activity Costs & Discounts")
st.write("Details on pricing and available discounts.")